from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from rake_nltk import Rake
import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

app = FastAPI()

class TaskPost(BaseModel):
    text: str

UNWANTED_WORDS = {
    "be", "is", "are", "was", "were", "being", "been",
    "do", "does", "did", "doing", "done",
    "have", "has", "had", "having",
    "make", "makes", "made", "making",
    "get", "gets", "got", "getting", "gotten",
    "go", "goes", "went", "gone", "going",
    "come", "comes", "came", "coming",
    "give", "gives", "gave", "given", "giving",
    "take", "takes", "took", "taken", "taking",
    "start", "starts", "started", "starting",
    "begin", "begins", "began", "begun", "beginning",
    "finish", "finishes", "finished", "finishing",
    "end", "ends", "ended", "ending",
    "keep", "keeps", "kept", "keeping",
    "stay", "stays", "stayed", "staying",
    "continue", "continues", "continued", "continuing",
    "stop", "stops", "stopped", "stopping",
    "try", "tries", "tried", "trying",
    "want", "wants", "wanted", "wanting",
    "need", "needs", "needed", "needing",
    "like", "likes", "liked", "liking",
    "love", "loves", "loved", "loving",
    "hate", "hates", "hated", "hating",
    "prefer", "prefers", "preferred", "preferring",
    "enjoy", "enjoys", "enjoyed", "enjoying",
    "feel", "feels", "felt", "feeling",
    "seem", "seems", "seemed", "seeming",
    "learn", "learns", "learned", "learning",
    "study", "studies", "studied", "studying",
    "read", "reads", "read", "reading",
    "write", "writes", "wrote", "written", "writing",
    "build", "builds", "built", "building",
    "create", "creates", "created", "creating",
    "develop", "develops", "developed", "developing",
    "improve", "improves", "improved", "improving",
    "work", "works", "worked", "working",
    "use", "uses", "used", "using",
    "help", "helps", "helped", "helping",
    "support", "supports", "supported", "supporting",
    "watch", "watches", "watched", "watching",
    "see", "sees", "saw", "seen", "seeing",
    "look", "looks", "looked", "looking",
    "focus", "focuses", "focused", "focusing",
    "avoid", "avoids", "avoided", "avoiding",
    "understand", "understands", "understood", "understanding",
    "think", "thinks", "thought", "thinking",
    "know", "knows", "knew", "known", "knowing",
    "explore", "explores", "explored", "exploring",
    "find", "finds", "found", "finding",
    "plan", "plans", "planned", "planning",
    "organize", "organizes", "organized", "organizing",
    "prepare", "prepares", "prepared", "preparing",
    "practice", "practices", "practiced", "practicing",
    "train", "trains", "trained", "training",
    "grow", "grows", "grew", "grown", "growing",
    "become", "becomes", "became", "becoming",
    "achieve", "achieves", "achieved", "achieving",
    "remember", "remembers", "remembered", "remembering",
    "try", "tries", "tried", "trying",
    "experience", "experiences", "experienced", "experiencing",

    "thing", "things", "stuff", "idea", "ideas", "goal", "goals",
    "project", "projects", "task", "tasks", "habit", "habits",
    "challenge", "challenges", "dream", "dreams", "plan", "plans",
    "time", "day", "week", "month", "year", "moment", "life",
    "way", "ways", "path", "journey", "step", "steps",
    "topic", "topics", "area", "areas", "field", "fields", "subject", "subjects",
    "activity", "activities", "aspect", "aspects", "point", "points",
    "process", "processes", "level", "levels", "phase", "phases",

    "good", "bad", "better", "best", "great", "awesome", "nice",
    "new", "old", "easy", "hard", "difficult", "simple", "complex",
    "important", "useful", "basic", "advanced", "essential", "necessary",
    "helpful", "productive", "efficient", "positive", "negative",
    "typical", "general", "real", "true", "false", "clear", "strong", "weak",
    "smart", "fun", "boring", "motivating", "inspiring", "big", "small",

    "really", "very", "just", "always", "never", "sometimes", "often", "rarely",
    "soon", "now", "then", "later", "before", "after", "already", "still",
    "maybe", "probably", "usually", "almost", "again", "somehow", "actually", "basically",

    "and", "or", "but", "because", "so", "if", "although", "though", "while",
    "when", "where", "as", "than", "since", "until", "with", "without", "for",
    "from", "to", "in", "on", "at", "by", "about", "of", "into", "onto",
    "over", "under", "between", "within", "among", "through", "across", "upon",

    "some", "more", "most", "many", "much", "few", "all", "any", "each", "every",
    "no", "not", "none", "this", "that", "these", "those", "it", "its", "their",
    "my", "your", "his", "her", "our", "i", "you", "he", "she", "we", "they",
    "me", "him", "them", "us", "mine", "yours", "ours", "theirs",
    "one", "two", "three", "first", "second", "third", "other", "another", "same",

    "can", "could", "should", "would", "will", "shall", "may", "might", "must",

    "a", "an", "the",
    
    "lol", "lmao", "rofl", "omg", "wtf", "idk", "ikr", "tbh", "btw", "brb", "afaik", "fyi", "smh",
    "yolo", "nah", "yeah", "yep", "nope", "alright", "ok", "okay", "ayy", "eh", "yo", "hey",
    "sup", "dude", "bro", "sis", "fam", "homie", "buddy", "pal", "mate", "man", "girl", "guy",
    "stuff", "thing", "things", "kinda", "sorta", "hella", "super", "duper", "crazy", "mad",
    "cool", "lit", "dope", "sick", "fire", "chill", "legit", "rad", "tight", "bomb", "banger",
    "basic", "extra", "lowkey", "highkey", "salty", "cringe", "weird", "sus", "sketchy",
    "bored", "tired", "lazy", "meh", "blah", "ugh", "eek", "yikes", "ew", "ouch", "oops",
    "woo", "yay", "nah", "huh", "hmm", "uh", "uhh", "umm", "whoa", "whoops", "nah", "yo",
    "brother", "sister", "bae", "boo", "babe", "hubby", "wifey", "daddy", "mommy",

    "put", "puts", "putting", 
    "set", "sets", "setting", 
    "turn", "turns", "turned", "turning",
    "move", "moves", "moved", "moving",
    "let", "lets", "letting",
    "call", "calls", "called", "calling",
    "ask", "asks", "asked", "asking",
    "tell", "tells", "told", "telling",
    "hear", "hears", "heard", "hearing",
    "say", "says", "said", "saying",
    "talk", "talks", "talked", "talking",
    "speak", "speaks", "spoke", "spoken", "speaking",
    "mean", "means", "meant", "meaning",
    "show", "shows", "showed", "shown", "showing",
    "hold", "holds", "held", "holding",
    "bring", "brings", "brought", "bringing",
    "buy", "buys", "bought", "buying",
    "sell", "sells", "sold", "selling",
    "send", "sends", "sent", "sending",
    "cut", "cuts", "cutting",
    "hit", "hits", "hitting",
    "eat", "eats", "ate", "eaten", "eating",
    "drink", "drinks", "drank", "drunk", "drinking",
    "sleep", "sleeps", "slept", "sleeping",
    "run", "runs", "ran", "run", "running",
    "walk", "walks", "walked", "walking",
    "drive", "drives", "drove", "driven", "driving",
    "break", "breaks", "broke", "broken", "breaking",
    "fix", "fixes", "fixed", "fixing",
    "check", "checks", "checked", "checking",
    "choose", "chooses", "chose", "chosen", "choosing",
    "decide", "decides", "decided", "deciding",
    "happen", "happens", "happened", "happening",
    "change", "changes", "changed", "changing",
    "play", "plays", "played", "playing",
    "win", "wins", "won", "winning",
    "lose", "loses", "lost", "losing",
    "open", "opens", "opened", "opening",
    "close", "closes", "closed", "closing",
    "wait", "waits", "waited", "waiting",
    "serve", "serves", "served", "serving",
    "cost", "costs", "costing",
    "pay", "pays", "paid", "paying",
    "catch", "catches", "caught", "catching",
    "draw", "draws", "drew", "drawn", "drawing",
    "fall", "falls", "fell", "fallen", "falling",
    "hide", "hides", "hid", "hidden", "hiding",
    "hang", "hangs", "hung", "hanging",
    "lift", "lifts", "lifted", "lifting",
    "mix", "mixes", "mixed", "mixing",
    "pass", "passes", "passed", "passing",
    "push", "pushes", "pushed", "pushing",
    "pull", "pulls", "pulled", "pulling",
    "shake", "shakes", "shook", "shaken", "shaking",
    "shut", "shuts", "shutting",
    "spend", "spends", "spent", "spending",
    "stand", "stands", "stood", "standing",
    "throw", "throws", "threw", "thrown", "throwing",
    "wake", "wakes", "woke", "woken", "waking",
    "wear", "wears", "wore", "worn", "wearing",
    "knock", "knocks", "knocked", "knocking",
    "burn", "burns", "burned", "burning",
    "melt", "melts", "melted", "melting",
    "sink", "sinks", "sank", "sunk", "sinking",
    "smell", "smells", "smelled", "smelling",
    "taste", "tastes", "tasted", "tasting",
    "touch", "touches", "touched", "touching",
    "twist", "twists", "twisted", "twisting",
    "wave", "waves", "waved", "waving",
    "whisper", "whispers", "whispered", "whispering",
    "worry", "worries", "worried", "worrying",
    "yell", "yells", "yelled", "yelling",
    "zoom", "zooms", "zoomed", "zooming",

    "object", "objects", "element", "elements", 
    "piece", "pieces", "component", "components",
    "factor", "factors", "issue", "issues",
    "matter", "matters", "subject", "subjects",
    "notion", "notions", "entity", "entities",
    "unit", "units", "segment", "segments",
    "portion", "portions", "section", "sections",
    "side", "sides", "angle", "angles",
    "instance", "instances", "example", "examples",
    "case", "cases", "context", "contexts",
    "variety", "varies", "various", "difference", "differences",
    "whole", "wholes", "total", "totals",
    "rest", "rests", "remainder", "remainders",
    "majority", "majorities", "minority", "minorities",
    "handful", "handfuls", "couple", "couples",
    "pair", "pairs", "duo", "triple", "triples",
    "collection", "collections", "set", "sets",
    "series", "sequence", "sequences", "array", "arrays",
    "deal", "deals", "amount", "amounts", "quantity", "quantities",
    "variation", "variations", "version", "versions",
    "edition", "editions", "form", "forms",
    "mode", "modes", "manner", "manners",
    "option", "options", "choice", "choices",
    "variety", "varies", "category", "categories",
    "genre", "genres", "style", "styles",
    "model", "models", "template", "templates",
    "format", "formats", "structure", "structures",
    "framework", "frameworks", "blueprint", "blueprints",
    "outline", "outlines", "summary", "summaries",
    "synopsis", "synopses", "overview", "overviews",
    "gist", "essence", "core", "cores",
    "base", "bases", "foundation", "foundations",
    "root", "roots", "source", "sources",
    "aspect", "aspects", "facet", "facets",
    "angle", "angles", "perspective", "perspectives",
    "view", "views", "opinion", "opinions",
    "thought", "thoughts", "belief", "beliefs",
    "attitude", "attitudes", "mindset", "mindsets",
    "approach", "approaches", "method", "methods",
    "technique", "techniques", "strategy", "strategies",
    "tactic", "tactics", "plan", "plans",
    "scheme", "schemes", "design", "designs",
    "layout", "layouts", "arrangement", "arrangements",
    "order", "orders", "sequence", "sequences",
    "hierarchy", "hierarchies", "rank", "ranks",
    "level", "levels", "tier", "tiers",
    "class", "classes", "group", "groups",
    "bracket", "brackets", "division", "divisions",
    "segment", "segments", "sector", "sectors",
    "domain", "domains", "realm", "realms",
    "sphere", "spheres", "arena", "arenas",
    "territory", "territories", "zone", "zones",
    "region", "regions", "district", "districts",
    "vicinity", "vicinities", "locality", "localities",
    "spot", "spots", "site", "sites",
    "venue", "venues", "setting", "settings",
    "environment", "environments", "milieu", "milieus",
    "backdrop", "backdrops", "scene", "scenes",
    "stage", "stages", "platform", "platforms",
    "forum", "forums", "board", "boards",
    "network", "networks", "web", "webs",
    "chain", "chains", "link", "links",
    "bond", "bonds", "tie", "ties",
    "knot", "knots", "node", "nodes",
    "hub", "hubs", "center", "centers",
    "core", "cores", "nucleus", "nuclei",
    "heart", "hearts", "soul", "souls",
    "essence", "spirit", "spirits",
    "abstract", "abstracts", "concept", "concepts",
    "notion", "notions", "theory", "theories",
    "hypothesis", "hypotheses", "assumption", "assumptions",
    "presumption", "presumptions", "guess", "guesses",
    "estimate", "estimates", "approximation", "approximations",
    "guesswork", "speculation", "speculations",
    "hunch", "hunches", "feeling", "feelings",
    "inkling", "inklings", "suspicion", "suspicions",
    "vibe", "vibes", "aura", "auras",
    "impression", "impressions", "perception", "perceptions",
    "sense", "senses", "sensibility", "sensibilities",
    "emotion", "emotions", "sentiment", "sentiments",
    "mood", "moods", "temper", "tempers",
    "atmosphere", "atmospheres", "ambiance", "ambiances",
    "energy", "energies", "vibration", "vibrations",
    "frequency", "frequencies", "wavelength", "wavelengths",
    "dimension", "dimensions", "plane", "planes",
    "reality", "realities", "existence", "existences",
    "being", "beings", "entity", "entities",
    "creature", "creatures", "organism", "organisms",
    "lifeform", "lifeforms", "specimen", "specimens",
    "individual", "individuals", "person", "persons",
    "human", "humans", "homo", "sapiens",
    "body", "bodies", "figure", "figures",
    "frame", "frames", "physique", "physiques",
    "anatomy", "anatomies", "structure", "structures",
    "system", "systems", "organ", "organs",
    "tissue", "tissues", "cell", "cells",
    "molecule", "molecules", "atom", "atoms",
    "particle", "particles", "element", "elements",
    "compound", "compounds", "substance", "substances",
    "material", "materials", "matter", "matters",
    "fabric", "fabrics", "texture", "textures",
    "surface", "surfaces", "exterior", "exteriors",
    "interior", "interiors", "inside", "insides",
    "outside", "outsides", "edge", "edges",
    "border", "borders", "boundary", "boundaries",
    "perimeter", "perimeters", "frontier", "frontiers",
    "limit", "limits", "limitation", "limitations",
    "restriction", "restrictions", "constraint", "constraints",
    "rule", "rules", "regulation", "regulations",
    "law", "laws", "act", "acts",
    "statute", "statutes", "ordinance", "ordinances",
    "decree", "decrees", "edict", "edicts",
    "principle", "principles", "doctrine", "doctrines",
    "dogma", "dogmas", "creed", "creeds",
    "philosophy", "philosophies", "ideology", "ideologies",
    "belief", "beliefs", "faith", "faiths",
    "religion", "religions", "cult", "cults",
    "sect", "sects", "denomination", "denominations",
    "persuasion", "persuasions", "conviction", "convictions",
    "viewpoint", "viewpoints", "standpoint", "standpoints",
    "position", "positions", "stance", "stances",
    "posture", "postures", "pose", "poses",
    "gesture", "gestures", "signal", "signals",
    "sign", "signs", "symbol", "symbols",
    "mark", "marks", "token", "tokens",
    "indicator", "indicators", "clue", "clues",
    "hint", "hints", "cue", "cues",
    "suggestion", "suggestions", "implication", "implications",
    "insinuation", "insinuations", "innuendo", "innuendos",
    "allusion", "allusions", "reference", "references",
    "mention", "mentions", "citation", "citations",
    "quote", "quotes", "quotation", "quotations",
    "excerpt", "excerpts", "passage", "passages",
    "extract", "extracts", "portion", "portions",
    "fragment", "fragments", "snippet", "snippets",
    "segment", "segments", "section", "sections",
    "part", "parts", "piece", "pieces",
    "bit", "bits", "chunk", "chunks",
    "portion", "portions", "fraction", "fractions",
    "percentage", "percentages", "ratio", "ratios",
    "proportion", "proportions", "rate", "rates",
    "degree", "degrees", "extent", "extents",
    "scope", "scopes", "range", "ranges",
    "spectrum", "spectra", "gamut", "gamuts",
    "span", "spans", "reach", "reaches",
    "compass", "compasses", "breadth", "breadths",
    "width", "widths", "depth", "depths",
    "height", "heights", "length", "lengths",
    "distance", "distances", "measure", "measures",
    "dimension", "dimensions", "size", "sizes",
    "volume", "volumes", "capacity", "capacities",
    "magnitude", "magnitudes", "scale", "scales",
    "intensity", "intensities", "strength", "strengths",
    "force", "forces", "power", "powers",
    "energy", "energies", "vigor", "vigors",
    "dynamism", "dynamisms", "momentum", "momenta",
    "velocity", "velocities", "speed", "speeds",
    "acceleration", "accelerations", "deceleration", "decelerations",
    "rhythm", "rhythms", "tempo", "tempos",
    "pace", "paces", "rate", "rates",
    "frequency", "frequencies", "periodicity", "periodicities",
    "interval", "intervals", "gap", "gaps",
    "pause", "pauses", "break", "breaks",
    "interruption", "interruptions", "disruption", "disruptions",
    "hiatus", "hiatuses", "lull", "lulls",
    "respite", "respites", "recess", "recesses",
    "breather", "breathers", "rest", "rests",
    "relaxation", "relaxations", "leisure", "leisures",
    "downtime", "downtimes", "idle", "idles",
    "inactivity", "inactivities", "stasis", "stases",
    "stillness", "motionlessness", "immobility", "immobilities",
    "rigidity", "rigidities", "flexibility", "flexibilities",
    "elasticity", "elasticities", "plasticity", "plasticities",
    "malleability", "malleabilities", "ductility", "ductilities",
    "hardness", "softness", "roughness",    "gritty", "slippery", "sticky", "fuzzy", "blurry", "grainy",
    "murky", "hazy", "glossy", "matte", "slimy", "crunchy",
    "brittle", "mushy", "damp", "moist", "parched", "crispy",
    "flaky", "spongy", "chewy", "tender", "juicy", "dry",
    "greasy", "oily", "slick", "frigid", "scorching", "lukewarm",
    "chilly", "balmy", "humid", "muggy", "breezy", "windy",
    "still", "noisy", "quiet", "deafening", "echoey", "muffled",
    "pitchy", "melodic", "harmonic", "dissonant", "rhythmic",
    "catchy", "monotonous", "shrill", "deep", "nasal", "hoarse",
    "muted", "vibrant", "pastel", "neon", "fluorescent", "glowing",
    "iridescent", "sparkly", "dull", "faded", "vintage", "antique",
    "modern", "retro", "futuristic", "dated", "timeless", "classic",
    "trendy", "outdated", "fresh", "stale", "rotten", "ripe",
    "sour", "bitter", "sweet", "salty", "savory", "spicy",
    "mild", "pungent", "aromatic", "reeking", "fragrant", "musty",
    "earthy", "floral", "woody", "smoky", "burnt", "metallic",
    "chemical", "synthetic", "organic", "natural", "artificial",
    "fake", "genuine", "counterfeit", "authentic", "ersatz", "mock",
    "virtual", "digital", "analog", "pixelated", "HD", "blurry",
    "overexposed", "underexposed", "saturated", "desaturated",
    "contrasty", "flat", "sharp", "soft", "zoomed", "cropped",
    "angled", "posed", "candid", "staged", "scripted", "improvised",
    "rehearsed", "spontaneous", "calculated", "random", "intentional",
    "accidental", "purposeful", "meaningless", "significant", "trivial",
    "profound", "shallow", "deep", "superficial", "genuine", "fake",
    "pretend", "imaginary", "hypothetical", "theoretical", "practical",
    "abstract", "concrete", "vague", "specific", "ambiguous", "clear",
    "confusing", "enlightening", "mystifying", "obvious", "subtle",
    "overt", "covert", "explicit", "implicit", "direct", "indirect",
    "literal", "figurative", "sarcastic", "ironic", "satirical",
    "witty", "corny", "cheesy", "cliché", "original", "derivative",
    "innovative", "outdated", "groundbreaking", "revolutionary",
    "evolutionary", "regressive", "progressive", "conservative",
    "liberal", "radical", "moderate", "extreme", "neutral", "biased",
    "objective", "subjective", "factual", "fictional", "realistic",
    "surreal", "abstract", "literal", "metaphorical", "symbolic",
    "cryptic", "straightforward", "convoluted", "simplistic", "nuanced",
    "black", "white", "gray", "colorful", "monochrome", "vibrant",
    "drab", "gaudy", "tacky", "elegant", "sleek", "clunky",
    "ergonomic", "awkward", "intuitive", "confusing", "user-friendly",
    "buggy", "glitchy", "responsive", "laggy", "snappy", "overloaded",
    "streamlined", "bloated", "minimalist", "ornate", "plain",
    "decorative", "functional", "stylish", "dowdy", "trendy",
    "fashionable", "unfashionable", "comfy", "itchy", "breathable",
    "stiff", "flexible", "rigid", "flimsy", "sturdy", "fragile",
    "durable", "temporary", "permanent", "ephemeral", "everlasting",
    "finite", "infinite", "endless", "boundless", "limited",
    "unlimited", "restricted", "unrestricted", "conditional",
    "unconditional", "partial", "total", "complete", "incomplete",
    "finished", "unfinished", "perfected", "flawed", "impeccable",
    "defective", "pristine", "damaged", "mint", "worn", "used",
    "new", "old", "antique", "modern", "ancient", "prehistoric",
    "futuristic", "space-age", "medieval", "renaissance", "vintage",
    "retro", "nostalgic", "contemporary", "timeless", "dated",

    "absolutely", "completely", "totally", "utterly", "entirely",
    "wholly", "fully", "quite", "rather", "fairly", "pretty",
    "somewhat", "slightly", "barely", "hardly", "scarcely",
    "mostly", "mainly", "primarily", "usually", "normally",
    "typically", "genuinely", "truly", "literally", "figuratively",
    "honestly", "frankly", "seriously", "jokingly", "ironically",
    "sarcastically", "technically", "practically", "theoretically",
    "essentially", "basically", "fundamentally", "naturally",
    "obviously", "evidently", "apparently", "seemingly",
    "superficially", "outwardly", "ostensibly", "presumably",
    "supposedly", "allegedly", "reportedly", "arguably",
    "possibly", "perhaps", "maybe", "hopefully", "thankfully",
    "fortunately", "unfortunately", "regrettably", "sadly",
    "happily", "luckily", "mercifully", "ideally", "ultimately",
    "eventually", "gradually", "slowly", "quickly", "rapidly",
    "swiftly", "speedily", "promptly", "immediately", "instantly",
    "suddenly", "abruptly", "unexpectedly", "accidentally",
    "intentionally", "deliberately", "consciously", "subconsciously",
    "unwittingly", "inadvertently", "automatically", "reflexively",
    "spontaneously", "impulsively", "carefully", "carelessly",
    "recklessly", "cautiously", "prudently", "rashly", "hastily",
    "patiently", "calmly", "nervously", "anxiously", "eagerly",
    "enthusiastically", "halfheartedly", "reluctantly", "grudgingly",
    "willingly", "readily", "gladly", "cheerfully", "bitterly",
    "angrily", "furiously", "quietly", "silently", "loudly",
    "noisily", "softly", "gently", "roughly", "violently",
    "forcefully", "vigorously", "lazily", "idly", "actively",
    "passively", "assertively", "aggressively", "defensively",
    "politely", "rudely", "courteously", "respectfully", "disrespectfully",
    "formally", "informally", "casually", "seriously", "playfully",
    "jokingly", "mockingly", "sarcastically", "sincerely", "insincerely",

    "meh", "ugh", "oof", "yikes", "sheesh", "geez", "jeez", "jeepers",
    "crikey", "blimey", "gosh", "darn", "dang", "shoot", "frick", "heck",
    "fudge", "shucks", "drat", "golly", "egads", "zounds", "yoinks",
    "jeepers", "cripes", "goodness", "gracious", "lawd", "lordy", "heavens",
    "fiddlesticks", "phooey", "poppycock", "balderdash", "hogwash", "malarkey",
    "drivel", "twaddle", "claptrap", "nonsense", "rubbish", "codswallop",
    "bollocks", "pishposh", "tommyrot", "gibberish", "gobbledygook",
    "mumbojumbo", "hullabaloo", "kerfuffle", "hubbub", "brouhaha", "hoo-ha",
    "whoopee", "yippee", "woohoo", "yeehaw", "yolo", "swag", "fam", "bruh",
    "dude", "sis", "homie", "chill", "salty", "extra", "basic", "lit", "savage",
    "ghost", "clout", "vibe", "mood", "flex", "thirsty", "woke", "cancel",
    "ship", "stan", "simp", "incel", "yeet", "sus", "cap", "noob", "goat",
    "af", "fr", "smh", "tbh", "idk", "ikr", "nvm", "fyi", "imo", "imho",
    "tmi", "nsfw", "sfw", "dm", "irl", "ama", "tl;dr", "ftw", "gtfo", "stfu",
    "rofl", "lmao", "lmfao", "omg", "wtf", "fml", "nbd", "oop", "yass", "slay",
    "periodt", "snatched", "tea", "spill", "receipts", "clapback", "shade",
    "drag", "read", "fierce", "werk", "bih", "sis", "queen", "kiki", "wig",
    "dead", "deceased", "finna", "bouta", "gon", "tryna", "gonna", "wanna",
    "gotta", "hafta", "shoulda", "coulda", "woulda", "mighta", "musta",
    "sorta", "kinda", "outta", "lotsa", "dunno", "lemme", "gimme", "gotcha",
    "howdy", "aloha", "adios", "ciao", "peace", "later", "cya", "brb", "ttyl",
    "gr8", "2moro", "4eva", "b4", "ur", "u", "r", "y", "plz", "thx", "sry",
    "np", "kk", "luv", "xoxo", "bff", "bae", "boo", "hubby", "wifey", "zaddy",
    "mommy", "daddy", "sis", "bro", "fam", "squad", "crew", "gang", "peeps",
    "paradigm", "leverage", "synergy", "bandwidth", "circle back",
    "touch base", "deep dive", "ideate", "boil the ocean", "move the needle",
    "low-hanging fruit", "drill down", "core competency", "value add",
    "win-win", "out of pocket", "ping", "disconnect", "alignment",
    "deliverables", "streamline", "optimize", "incentivize", "monetize",
    "utilize", "actualize", "operationalize", "strategize", "prioritize",
    "gamify", "influence", "viral", "curate", "disrupt", "pivot", "iterate",
    "scale", "growth hack", "bleeding edge", "next-gen", "holistic",
    "ecosystem", "vertical", "horizontal", "granular", "robust", "agile",
    "scalable", "mission-critical", "turnkey", "best-of-breed", "seamless",
    "frictionless", "value proposition", "roi", "kpi", "okr", "sop", "eta",
    "asap", "tbd", "bs", "fyi", "nsfw", "tldr", "imo", "ama", "eli5", "smh",
    "irl", "fomo", "yolo", "fwiw", "tbh", "icymi", "lmk", "nvm", "og", "af",
    "sus", "cap", "simp", "stan", "ghost", "clout", "vibe", "mood", "extra",
    "salty", "lit", "savage", "woke", "cancel", "ship", "yeet", "flex", "tea",
    "spill", "receipts", "shade", "drag", "read", "fierce", "werk", "snatched",
    "periodt", "bih",

    "fuck", "fucks", "fucking", "fucked", "fucker", "fuckers", "motherfucker", "motherfuckers",
    "shit", "shits", "shitty", "bullshit", "horseshit", "shithead", "shitstorm", "shitload",
    "ass", "asses", "asshole", "assholes", "dumbass", "smartass", "lardass", "badass",
    "bitch", "bitches", "bitching", "sonofabitch", "bitchy", "bitchslap",
    "damn", "godamn", "goddamn", "damnit", "dammit",
    "cunt", "cunts", "cunty", "dick", "dicks", "dickhead", "dickface", "prick", "pricks",
    "cock", "cocks", "cocksucker", "cocky", "bellend", "wanker", "tosser",
    "pussy", "pussies", "twat", "twats", "vagina", "vaginas", "clit", "clitoris",
    "bastard", "bastards", "douche", "douchebag", "douchecanoe", "douchewaffle",
    "whore", "whores", "slut", "sluts", "slutty", "ho", "hos", "hooker", "hookers",
    "retard", "retarded", "spaz", "spastic", "moron", "idiot", "imbecile", "cretin",
    "dumb", "dummy", "stupid", "retard", "lame", "lameass", "loser", "losers",
    "scum", "scumbag", "trash", "garbage", "pig", "swine", "animal", "beast",
    "freak", "freaks", "weirdo", "weirdos", "psycho", "psychopath", "sociopath",
    "nazi", "nazis", "racist", "sexist", "homophobe", "transphobe", "bigot",
    "pedo", "pedophile", "rapist", "murderer", "criminal", "thug", "thugs",
    "junkie", "druggie", "addict", "alcoholic", "drunk", "drunkard",
    "kill", "kills", "killer", "killing", "murder", "murders", "murderer", "stab", "stabs",
    "shoot", "shoots", "shooter", "shooting", "die", "dies", "dying", "death", "dead",
    "suicide", "suicidal", "hang", "hangs", "hanging", "bleed", "bleeding", "blood", "bloody",
    "bomb", "bombs", "terrorist", "terrorism", "attack", "attacks", "hit", "hits", "hitting",
    "punch", "punches", "punching", "fight", "fights", "fighting", "war", "wars", "battle",
    "battles", "destroy", "destroys", "destroying", "destruction", "harm", "harms", "harming",
    "hurt", "hurts", "hurting", "pain", "pains", "painful", "torture", "tortures", "torturing",
    "abuse", "abuses", "abusing", "rape", "rapes", "raping", "rapist", "abuser", "abusive",
    "poop", "poops", "poopy", "crap", "craps", "crappy", "defecate", "defecates", "defecating",
    "fart", "farts", "farting", "flatulence", "flatulent", "pee", "pees", "peeing", "piss", "pisses",
    "pissing", "pissed", "urine", "urinate", "urinates", "urinating", "cum", "cums", "cumming",
    "semen", "sperm", "ejaculate", "ejaculates", "ejaculating", "orgasm", "orgasms", "orgasmic",
    "penis", "penises", "dildo", "dildos", "vibrator", "vibrators", "condom", "condoms",
    "anal", "anus", "butt", "butts", "butthole", "buttholes", "ass", "asses", "asshole", "assholes",
    "nigga", "niggas", "nigger", "niggers", "chink", "chinks", "gook", "gooks", "spic", "spics",
    "kike", "kikes", "wetback", "wetbacks", "redneck", "rednecks", "hillbilly", "hillbillies",
    "whitey", "cracker", "crackers", "honky", "honkies", "gypsy", "gypsies", "tranny", "trannies",
    "shemale", "shemales", "fag", "fags", "faggot", "faggots", "dyke", "dykes", "queer", "queers",
    "homo", "homos", "lesbo", "lesbos", "sissy", "sissies", "pansy", "pansies", "wuss", "wusses",
    "pussy", "pussies", "weakling", "weaklings", "coward", "cowards", "traitor", "traitors",
    "snake", "snakes", "backstabber", "backstabbers", "liar", "liars", "cheater", "cheaters",
    "fraud", "frauds", "fake", "fakes", "phony", "phonies", "poser", "posers", "wannabe", "wannabes",
    "blowjob", "blowjobs", "handjob", "handjobs", "titjob", "titjobs", "boob", "boobs", "tits", "titties",
    "breast", "breasts", "nipple", "nipples", "porn", "porno", "pornography", "xxx", "sexy", "sexier",
    "sexiest", "seduce", "seduces", "seducing", "seduction", "erotic", "erotica", "masturbate", "masturbates",
    "masturbating", "masturbation", "horny", "aroused", "arousal", "fetish", "fetishes", "bdsm", "kink", "kinky",
    "orgy", "orgies", "threesome", "foursome", "swinger", "swingers", "prostitute", "prostitutes", "escort",
    "escorts", "stripper", "strippers", "lapdance", "lapdances", "booty", "bootycall", "milf", "dilf",
    "cougar", "sugar daddy", "gold digger", "gold diggers", "incest", "incestuous", "pedophilia", "pedophile",
    "necrophilia", "bestiality", "zoophilia", "voyeur", "voyeurism", "exhibitionist", "exhibitionism",
    "supremacist", "supremacists", "white supremacist", "black supremacist", "racism", "racist", "racists",
    "sexism", "sexist", "sexists", "misogyny", "misogynist", "misogynistic", "misandry", "misandrist",
    "homophobia", "homophobic", "transphobia", "transphobic", "xenophobia", "xenophobic", "antisemitism",
    "antisemitic", "islamophobia", "islamophobic", "ableism", "ableist", "ageism", "ageist", "classism",
    "classist", "fatphobia", "fatphobic", "hate", "hates", "hated", "hating", "hater", "haters", "hateful",
    "bigotry", "bigot", "bigots", "intolerance", "intolerant", "discrimination", "discriminatory", "prejudice",
    "prejudiced", "stereotype", "stereotypes", "stereotyping", "oppression", "oppressive", "oppressor", "oppressors",
    "colonizer", "colonizers", "imperialist", "imperialists", "fascist", "fascists", "nazi", "nazis", "kkk",
    "skinhead", "skinheads", "extremist", "extremists", "terrorist", "terrorists", "radical", "radicals",
    "zealot", "zealots", "fanatic", "fanatics", "cultist", "cultists", "brainwash", "brainwashes", "brainwashing",
    "frick", "fricks", "frigging", "frigger", "friggers", "motherfrigger", "motherfriggers",
    "shiz", "shizz", "shizzle", "shite", "bullshite", "horseshite", "shitehead", "shitestorm",
    "arse", "arses", "arsehole", "arseholes", "dumbarse", "smartarse", "lardarse", "badarse",
    "beeep", "bleep", "bleeps", "bleeping", "bleeped", "expletive", "expletives", "swear", "swears",
    "swearing", "swore", "sworn", "profanity", "profanities", "cuss", "cusses", "cussing", "cussed",
    "curse", "curses", "cursing", "cursed", "obscenity", "obscenities", "vulgarity", "vulgarities",
    "filth", "filthy", "dirt", "dirty", "smut", "smutty", "lewd", "lewdness", "crude", "crudeness",
    "raunchy", "raunch", "coarse", "coarseness", "tasteless", "tastelessness", "offensive", "offensiveness",
    "derogatory", "derogatoriness", "insult", "insults", "insulting", "insulted", "insulter", "insulters",
    "demean", "demeans", "demeaning", "demeaned", "degrade", "degrades", "degrading", "degraded",
    "humiliate", "humiliates", "humiliating", "humiliated", "humiliation", "shame", "shames", "shaming",
    "shamed", "disgrace", "disgraces", "disgracing", "disgraced", "disgraceful", "scandal", "scandals",
    "scandalous", "outrage", "outrages", "outraging", "outraged", "outrageous", "abomination", "abominations",
    "abominable", "atrocity", "atrocities", "atrocious", "horror", "horrors", "horrible", "horrific",
    "monstrosity", "monstrosities", "monstrous", "evil", "evils", "evildoer", "evildoers", "wicked", "wickedness",
    "sin", "sins", "sinner", "sinners", "sinful", "sinfulness", "immoral", "immorality", "unethical", "unethically",
    "corrupt", "corrupts", "corrupting", "corrupted", "corruption", "depraved", "depravity", "pervert", "perverts",
    "perverted", "perversion", "deviant", "deviants", "deviance", "sicko", "sickos", "creep", "creeps", "creepy",
    "weirdo", "weirdos", "freak", "freaks", "freaky", "monster", "monsters", "monstrous", "demon", "demons",
    "demonic", "satan", "satanic", "devil", "devils", "devilish", "hellish", "infernal", "damned", "damnation",
    "doom", "dooms", "doomed", "dooming", "curse", "curses", "cursed", "cursing", "hex", "hexes", "hexed", "hexing",
    "jinx", "jinxes", "jinxed", "jinxing", "omen", "omens", "ominous", "portent", "portents", "portentous",
    "prophecy", "prophecies", "prophetic", "apocalypse", "apocalyptic", "armageddon", "cataclysm", "cataclysmic",
    "disaster", "disasters", "disastrous", "calamity", "calamities", "calamitous", "tragedy", "tragedies", "tragic",
    "catastrophe", "catastrophes", "catastrophic", "havoc", "havocs", "wreak", "wreaks", "wreaking", "wreaked",
    "destruction", "destructive", "destroy", "destroys", "destroying", "destroyed", "destroyer", "destroyers",
    "annihilation", "annihilate", "annihilates", "annihilating", "annihilated", "annihilator", "annihilators",
    "obliteration", "obliterate", "obliterates", "obliterating", "obliterated", "eradication", "eradicate",
    "eradicates", "eradicating", "eradicated", "extinction", "extinct", "extinguish", "extinguishes", "extinguishing",
    "extinguished", "extinguisher", "extinguishers", "termination", "terminate", "terminates", "terminating",
    "terminated", "terminator", "terminators", "execution", "execute", "executes", "executing", "executed",
    "executioner", "executioners", "slaughter", "slaughters", "slaughtering", "slaughtered", "slaughterhouse",
    "slaughterhouses", "massacre", "massacres", "massacring", "massacred", "genocide", "genocidal", "holocaust",
    "holocausts", "pogrom", "pogroms", "ethnic cleansing", "war crime", "war crimes", "crime against humanity",
    "crimes against humanity", "torture", "tortures", "torturing", "tortured", "torturer", "torturers", "torturous",
    "torment", "torments", "tormenting", "tormented", "tormentor", "tormentors", "agony", "agonies", "agonizing",
    "agonized", "anguish", "anguishes", "anguishing", "anguished", "suffering", "suffer", "suffers", "suffered",
    "misery", "miseries", "miserable", "wretched", "wretchedness", "despair", "despairs", "despairing", "despaired",
    "hopeless", "hopelessness", "forlorn", "forlornness", "desolation", "desolate", "desolates", "desolating",
    "desolated", "desolater", "desolaters", "despair", "despairs", "despairing", "despaired", "desperation",
    "desperate", "desperately", "desperateness", "helpless", "helplessness", "powerless", "powerlessness",
    "weakness", "weaknesses", "weak", "weaker", "weakest", "feeble", "lot"
}

rake = Rake()

@app.post("/extract-interests")
def extract_interests(task_post: TaskPost):
    try:
        text = task_post.text
        rake.extract_keywords_from_text(text)
        raw_phrases = rake.get_ranked_phrases()

        words = []
        for phrase in raw_phrases:
            for word in phrase.lower().split():
                if word not in UNWANTED_WORDS and word.isalpha():
                    words.append(word)

        keywords = list(dict.fromkeys(words))

        return {"interests": keywords}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))